// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAC7G_QHCDHY1RNxYJmh5ypTPn2b0qNXs',
    appId: '1:681277496146:web:fb8f0a0f5d8d63789d388b',
    messagingSenderId: '681277496146',
    projectId: 'course-scheduler-1a8d3',
    authDomain: 'course-scheduler-1a8d3.firebaseapp.com',
    storageBucket: 'course-scheduler-1a8d3.appspot.com',
    measurementId: 'G-SNWYN32B2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByVYDhSHUl3uf7rAt8LhzEv66pjNNJa1M',
    appId: '1:681277496146:android:250a3e7bd9e424659d388b',
    messagingSenderId: '681277496146',
    projectId: 'course-scheduler-1a8d3',
    storageBucket: 'course-scheduler-1a8d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNfRc6lmlROMi0_4F_SS8nV35Sm3YtnbE',
    appId: '1:681277496146:ios:843543b697b2daf79d388b',
    messagingSenderId: '681277496146',
    projectId: 'course-scheduler-1a8d3',
    storageBucket: 'course-scheduler-1a8d3.appspot.com',
    iosBundleId: 'com.example.courseScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNfRc6lmlROMi0_4F_SS8nV35Sm3YtnbE',
    appId: '1:681277496146:ios:843543b697b2daf79d388b',
    messagingSenderId: '681277496146',
    projectId: 'course-scheduler-1a8d3',
    storageBucket: 'course-scheduler-1a8d3.appspot.com',
    iosBundleId: 'com.example.courseScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAC7G_QHCDHY1RNxYJmh5ypTPn2b0qNXs',
    appId: '1:681277496146:web:274a3fe44116f02a9d388b',
    messagingSenderId: '681277496146',
    projectId: 'course-scheduler-1a8d3',
    authDomain: 'course-scheduler-1a8d3.firebaseapp.com',
    storageBucket: 'course-scheduler-1a8d3.appspot.com',
    measurementId: 'G-1X9VCF1BD6',
  );
}
